### ISSUE TITLE
SSL certificate error- SSL CERTIFICATE_VERIFY_FAILED - mageto api

### ISSUE THREAD

**Issue by rakeshlanjewar** [fulfilio/python-magento#19]
If you face this problem then please put this code before calling the client

# not to verify ssl
import os, ssl
if (not os.environ.get('PYTHONHTTPSVERIFY', '') and
    getattr(ssl, '_create_unverified_context', None)):
    ssl._create_default_https_context = ssl._create_unverified_context

**Comment by rakeshlanjewar** [comment]
this is for future reference !

**Comment by pljspahn** [comment]
You can also use the chain.pem file from the host by referencing it from an environment variable.

    SSL_CERT_FILE=/path/to/yourfile/chain.pem

**Comment by pljspahn** [comment]
Adding to my previous comment - which I think is probably wrong here, as I had two SSL cert errors I was getting. In my code I call my magento site directly for some images using `requests` which was solved by putting the path to the chain file in my `.env` file. That fixed that part, but I hadn't bothered to realize that using this library didn't honor that. 

I'd hope to dig in and modify this library to be able to provide the proper cert file so that I'm not just disabling verification, but I got shit to do, and just disabling it for now using via @rakeshlanjewar comment is what I'm going to use for now.
